[[nulecule-a-composite-container-based-application-specification]]
Nulecule: A Composite Container-based Application Specification
---------------------------------------------------------------

*_/NOO-le-kyul/_* _(n.)_ – a made-up word meaning
"__http://simpsons.wikia.com/wiki/Made-up_words[the mother of all atomic
particles]__." Sounds like "molecule". But different.

*Package once. Run anywhere.* With pluggable orchestration providers you
can package your application to run on OpenShift, Kubernetes, Docker
Compose, Helios, Panamax, Docker Machine, etc. and allow the user to
choose the target when deployed.

*Compose applications from a catalog.* No need to re-package common
services. Create composite applications by referencing other
Nulecule-compliant apps. Adding a well-designed, orchestrated database
is simply a reference to another container image.

*MSI Installer for containers.* Replace your shell script and deployment
instructions with some metadata.

*Change runtime parameters for different environments.* No need to edit
files before deployment. Users can choose interactive or unattended
deployment. Guide web interface users with parameter metadata to
validate user input and provide descriptive help.

[[problem-statement]]
Problem Statement
~~~~~~~~~~~~~~~~~

Currently there is no standard mechanism to define a composite
multi-container application or composite service composed of aggregate
pre-defined building blocks spanning multiple hosts and clustered
deployments. In addition, the associated metadata and artifact
management requires separate processes outside the context of the
application itself.

[[what-is-nulecule]]
What is Nulecule?
~~~~~~~~~~~~~~~~~

Nulecule defines a pattern and model for packaging complex
multi-container applications, referencing all their dependencies,
including orchestration metadata in a container image for building,
deploying, monitoring, and active management.

The Nulecule specification enables complex applications to be defined,
packaged and distributed using standard container technologies. The
resulting container includes dependencies while supporting multiple
orchestration providers and ability to specify resource requirements.
The Nulecule specification also supports aggregation of multiple
composite applications. The Nulecule specification is container and
orchestration agnostic, enabling the use of any container and
orchestration engine.

[[nulecule-specification]]
Nulecule Specification
~~~~~~~~~~~~~~~~~~~~~~

The Nulecule Specification is developed as a community effort on github.

The Team uses a mailing lists hosted by Red Hat.

If you want to contribute to the Nulecule Specification itself, we
welcome you at the spec's repo.

[[highlights]]
Highlights
^^^^^^^^^^

* Application description and context maintained within a single
container through extensible metadata
* Composable definition of complex applications through inheritance and
composition of containers into a single, standards-based, portable
description.
* Simplified dependency management for the most complex applications
through a directed graph to reflect relationships.
* Container and orchestration engine agnostic, enabling the use of any
container technology and/or orchestration technology

[[releases]]
Releases
^^^^^^^^

* latest, 0.0.2 human readable version, machine readable version
* 0.0.1-alpha Archive

[[the-big-picture]]
“The Big Picture”
~~~~~~~~~~~~~~~~~

[[deployment-user-experience]]
Deployment User Experience
~~~~~~~~~~~~~~~~~~~~~~~~~~

Here's an example using the
https://github.com/projectatomic/atomicapp[atomicapp reference
implementation] with a kubernetes provider.

[[option-1-interactive]]
Option 1: interactive
^^^^^^^^^^^^^^^^^^^^^

Run the image. You will be prompted to provide required values that are
missing from the default configuration.

-------------------------------------------
[sudo] atomic run projectatomic/helloapache
-------------------------------------------

[[option-2-unattended]]
Option 2: unattended
^^^^^^^^^^^^^^^^^^^^

1.  Create file `answers.conf` with these contents:
+
------------------------------------------------------------------
[general]
provider = kubernetes

[helloapache-app]
image = centos/httpd # optional: choose a different image
hostport = 80        # optional: choose a different port to expose
------------------------------------------------------------------
2.  Run the application from the current working directory
+
---------------------------------------------
$ [sudo] atomic run projectatomic/helloapache
...
helloapache
---------------------------------------------

[[option-3-install-and-run]]
Option 3: install and run
^^^^^^^^^^^^^^^^^^^^^^^^^

You may want to download the application, review, edit the answerfile
then run.

1.  Download the application files using `atomic install`
+
-----------------------------------------------
[sudo] atomic install projectatomic/helloapache
-----------------------------------------------
2.  Rename `answers.conf.sample`
+
-----------------------------------
mv answers.conf.sample answers.conf
-----------------------------------
3.  Edit `answers.conf`, review files if desired and run
+
---------------------------------------------
$ [sudo] atomic run projectatomic/helloapache
...
helloapache
---------------------------------------------

[[developer-user-experience]]
Developer User Experience
~~~~~~~~~~~~~~~~~~~~~~~~~

See the
https://github.com/projectatomic/nulecule/blob/master/docs/getting-started.md[Getting
Started with Nulecule guide].

[[implementations]]
Implementations
~~~~~~~~~~~~~~~

This is only a specification. Implementations may be written in any
language. See
https://github.com/projectatomic/nulecule/blob/master/docs/implementation_guide.md[implementation
guide] for more details.

*Reference implementation* https://github.com/projectatomic/atomicapp

[[developer-tooling]]
Developer tooling
^^^^^^^^^^^^^^^^^

Developer tooling is TBD. There is some work planned for
http://devassistant.org/[DevAssistant].

[[contributing]]
Contributing
^^^^^^^^^^^^

Please review the
https://github.com/projectatomic/nulecule/blob/master/CONTRIBUTING.md[contributing
guidelines] before submitting pull requests.

[[communication-channels]]
Communication channels
^^^^^^^^^^^^^^^^^^^^^^

* IRC: #nulecule (On Freenode)
* Mailing List:
https://www.redhat.com/mailman/listinfo/container-tools[container-tools@redhat.com]
